### ISSUE TITLE
Both commands upsidedown and uʍopǝpᴉsdn should work both normal and upside-down texts

### ISSUE THREAD

**Issue by antononcube** [lizmat/Acme-Text-UpsideDown#1]
Let me say first: Thanks for programming `Acme::Text::UpsideDown` ! It is extremely useful and needed!

I think both commands `upsidedown` and `uʍopǝpᴉsdn` should work on both normal and upside-down texts.

We can say that both commands are involutional. For example, I would expect this command:

```perl6
upsidedown upsidedown 'the wolf, the ram, and the raccoon went into a socket'
```

to produce the result:

```perl6
'the wolf, the ram, and the raccoon went into a socket'
```

Another motivational use case is converting upside-down texts "from the  web" using a command line one-liner to produce the straight text. For example:

```shell
 raku -M Acme::Text::UpsideDown -e "say upsidedown 'oᴉ˙ǝɯɔɐ@ᘔ⇂˙ǝop˙uɥoſ̣'"
```

should give "john.doe.12@acme.io".

**Comment by lizmat** [comment]
Release 0.0.6 fixes this **and** adds a CLI: https://raku.land/zef:lizmat/Acme::Text::UpsideDown

**Comment by antononcube** [comment]
Thank you for your prompt resolving of this issue/request! (I just tried the CLI.)
