### ISSUE TITLE
CLI does not work because it refers explicitly to ver<0.0.6>

### ISSUE THREAD

**Issue by antononcube** [lizmat/Acme-Text-UpsideDown#3]
The CLI script has the explicit reference:

```
use Acme::Text::UpsideDown:ver<0.0.6>:auth<zef:lizmat>;
```

hence after installing "ver<0.0.7>" when trying:

```
ud aardvark
```

we get messages like:

> Could not find Acme::Text::UpsideDown:ver<0.0.6>:auth<zef:lizmat> in: [...]

(Instead of "ʞɹɐʌpɹɐɐ".)

**Comment by lizmat** [comment]
Thanks for the report!

Fixed in https://raku.land/zef:lizmat/Acme::Text::UpsideDown?v=0.0.8
